serviceAccount:
  create: false
  name: ${k8s_service_account_name}
  annotations:
    %{ if cloud_provider == "gke" }iam.gke.io/gcp-service-account: ${gcp_service_account_email}%{ endif }
    %{ if cloud_provider == "eks" }eks.amazonaws.com/role-arn: ${aws_role_arn}%{ endif }


# Explicitly disable testFramework to avoid nil pointer in Helm chart
testFramework:
  enabled: false
  image: "bats/bats"
  securityContext:
    runAsUser: 1000

adminUser: admin
adminPassword: ${grafana_admin_password}

persistence:
  enabled: true
  size: 1Gi

service:
  type: ClusterIP # Keeping service type as ClusterIP, assuming ingress will handle external access
  port: 80
  targetPort: 3000
  annotations: {} # Removing service annotations as they are moved to ingress

ingress:
  enabled: false
  ingressClassName: ${ingress_class_name}
  annotations:
    cert-manager.io/issuer: ${cert_issuer_name}
    external-dns.alpha.kubernetes.io/hostname: grafana.${monitoring_domain} # Replace with your Grafana domain name (e.g., grafana.yourdomain.com)

env:
  GF_FEATURE_TOGGLES_ENABLE: publicDashboards
  GF_LOG_LEVEL: info
  GF_AUTH_ANONYMOUS_ENABLED: "false"

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      # Default Tenant Data Sources
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://monitoring-prometheus-server:80
        isDefault: true
        jsonData:
          httpMethod: POST
          timeInterval: 15s
          httpHeaderName1: 'X-Scope-OrgID'
        secureJsonData:
          httpHeaderValue1: 'default'

      - name: Loki
        type: loki
        access: proxy
        url: http://monitoring-loki-gateway:80
        jsonData:
          maxLines: 1000
          httpHeaderName1: 'X-Scope-OrgID'
        secureJsonData:
          httpHeaderValue1: 'default'

      - name: Mimir
        type: prometheus
        access: proxy
        url: http://monitoring-mimir-nginx:80/prometheus
        jsonData:
          httpMethod: POST
          timeInterval: 15s
          httpHeaderName1: 'X-Scope-OrgID'
        secureJsonData:
          httpHeaderValue1: 'default'

      - name: Tempo
        type: tempo
        access: proxy
        url: http://monitoring-tempo-query-frontend:3200
        jsonData:
          httpMethod: GET
          tracesToLogsV2: {}
          datasourceUid: Loki
          spanStartTimeShift: '-1h'
          spanEndTimeShift: '1h'
          filterByTraceID: true
          filterBySpanID: false
          httpHeaderName1: 'X-Scope-OrgID'
        secureJsonData:
          httpHeaderValue1: 'default'
        tracesToMetrics:
          datasourceUid: Prometheus
        serviceMap:
          datasourceUid: Prometheus
        nodeGraph:
          enabled: true

      # Webank Tenant Data Sources
      - name: Webank-Prometheus
        type: prometheus
        access: proxy
        url: http://monitoring-prometheus-server:80
        jsonData:
          httpMethod: POST
          timeInterval: 15s
          httpHeaderName1: 'X-Scope-OrgID'
        secureJsonData:
          httpHeaderValue1: 'webank'

      - name: Webank-Loki
        type: loki
        access: proxy
        url: http://monitoring-loki-gateway:80
        jsonData:
          maxLines: 1000
          httpHeaderName1: 'X-Scope-OrgID'
        secureJsonData:
          httpHeaderValue1: 'webank'

      - name: Webank-Mimir
        type: prometheus
        access: proxy
        url: http://monitoring-mimir-nginx:80/prometheus
        jsonData:
          httpMethod: POST
          timeInterval: 15s
          httpHeaderName1: 'X-Scope-OrgID'
        secureJsonData:
          httpHeaderValue1: 'webank'

      - name: Webank-Tempo
        type: tempo
        access: proxy
        url: http://monitoring-tempo-query-frontend:3200
        jsonData:
          httpMethod: GET
          tracesToLogsV2: {}
          datasourceUid: Webank-Loki
          spanStartTimeShift: '-1h'
          spanEndTimeShift: '1h'
          filterByTraceID: true
          filterBySpanID: false
          httpHeaderName1: 'X-Scope-OrgID'
        secureJsonData:
          httpHeaderValue1: 'webank'
        tracesToMetrics:
          datasourceUid: Webank-Prometheus
        serviceMap:
          datasourceUid: Webank-Prometheus
        nodeGraph:
          enabled: true
